### ISSUE TITLE
Make Stripe calls idempotent

### ISSUE THREAD

**Issue by willglynn** [star-fleet-tours/reservation-system#1]
Right now, [`routes.php` reads](https://github.com/star-fleet-tours/reservation-system/blob/master/src/routes.php#L91-L103):

```php
        \Stripe\Stripe::setApiKey(getenv('STRIPE_PRIVATE_KEY'));
        $customer = \Stripe\Customer::create([
            'source' => $_POST['stripeToken'],
            'email' => $reservation['reservationEmail'],
        ]);
        $charge = \Stripe\Charge::create([
            'amount' => $reservation['totalPaymentDue'] * 100,
            'currency' => 'usd',
            'description' => "Star Fleet Tours " . strtoupper($currentMission) . " Mission",
            'statement_descriptor' => "SFT " . strtoupper($currentMission),
            'customer' => $customer->id,
        ]);
```

If the user submits the form twice, they'll get charged twice and create two reservations as a result. The review page doesn't disable the button on submission, so an accidental double click is likely to trigger this behavior.

Stripe supports [idempotent requests](https://stripe.com/docs/api/idempotent_requests). One way to use this would be to make `/review` assign a reservation ID (e.g. 1001), have `/complete` pass this to Stripe as `Idempotency-Key: create-customer-1001` and `Idempotency-Key: create-charge-1001`, and finally `HSETNX` reservation 1001. The `Idempotency-Key:`s would allow the Stripe calls to be safely retransmitted without creating duplicate records, and `HSETNX` would allow `/complete` to conditionally update inventory iff this request was the request which created the reservation.

(Additionally, assigning a reservation ID prior to creating the Stripe charge would allow the Stripe charge to include the reservation ID, which is a nice side effect.)

**Comment by EvanDotPro** [comment]
Didn't know about Stripe's idempotency key, thanks!
