### ISSUE TITLE
Fix /complete race condition

### ISSUE THREAD

**Issue by willglynn** [star-fleet-tours/reservation-system#2]
`/complete` has a [TOCTOU](https://en.wikipedia.org/wiki/Time-of-check_to_time-of-use) race condition:

```php
$reservationID = $container->get('hashids')->encode(
    count($container->get('redis')->zRevRangeByScore("$currentMission:reservations", '+inf', '-inf')) + 1001
);
$container->get('redis')->hMSet("$currentMission:reservation:$reservationID", $reservation);
```

If two users complete a reservation at the same time, they could both execute `ZREVRANGEBYSCORE`, both decide to use the same reservation ID, and both execute `HMSET` for the same `$currentMission:reservation:$reservationID`. The second `HMSET` would overwrite the first, causing the first reservation to be lost.

One solution would be to have a common `reservation_id` key, and have Redis assign IDs using [`INCR`](https://redis.io/commands/incr). This resolves the race by serializing reservation ID assignment.

Another solution would be a loop using `ZREVRANGEBYSCORE` to provisionally assign a reservation ID followed by [`HSETNX`](https://redis.io/commands/hsetnx) to record the reservation, and break if `HSETNX` indicates success. This resolves the race by serializing reservation storage, but requires a loop.

**Comment by EvanDotPro** [comment]
Thank you for the review and spotting this. Very helpful to have another set of eyes!

**Comment by CAM-Gerlach** [comment]
@EvanDotPro You're still alive! I was getting really worried about you, man, didn't want you to end up in the ER like me or something.
